# Generated by Django 4.1.3 on 2022-12-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('Catnumb', models.IntegerField(primary_key=True, serialize=False)),
                ('Cat_name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('Part_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Part', models.CharField(max_length=50)),
                ('Cat', models.IntegerField()),
            ],
        ),
    ]
